# Generated by Django 4.2.7 on 2023-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='menu_item/images')),
                ('category', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
    ]
